import { GameData } from "@/context/interface";

const ROOT_PATH = "/images/games/";

export const DUMMY_GAME_LIST: GameData = {
  "1": {
    id: "1",
    name: "Ultima 1D",
    providerID: "14",
    category: "Jackpots",
    banner: `${ROOT_PATH}ultima-1d.png`,
  },
  "2": {
    id: "2",
    name: "GT Sword",
    providerID: "9",
    category: "Jackpots",
    banner: `${ROOT_PATH}gt-sword.png`,
  },
  "3": {
    id: "3",
    name: "Genie Bow",
    providerID: "18",
    category: "Others",
    banner: `${ROOT_PATH}genie-bow.png`,
  },
  "4": {
    id: "4",
    name: "Rune Blade",
    providerID: "2",
    category: "Others",
    banner: `${ROOT_PATH}rune-blade.png`,
  },
  "5": {
    id: "5",
    name: "Stone Bato",
    providerID: "15",
    category: "Table Games",
    banner: `${ROOT_PATH}online-sabong.png`,
  },
  "6": {
    id: "6",
    name: "Patrick Star",
    providerID: "1",
    category: "Others",
    banner: `${ROOT_PATH}oblivion-saga.png`,
  },
  "7": {
    id: "7",
    name: "Bread Jackpot",
    providerID: "7",
    category: "Jackpots",
    banner: `${ROOT_PATH}bread-winner.png`,
  },
  "8": {
    id: "8",
    name: "Gave Jackpot",
    providerID: "5",
    category: "Jackpots",
    banner: `${ROOT_PATH}oblivion-saga.png`,
  },
  "9": {
    id: "9",
    name: "Wasak Game",
    providerID: "3",
    category: "Others",
    banner: `${ROOT_PATH}rune-blade.png`,
  },
  "10": {
    id: "10",
    name: "Team Wasak Challenge",
    providerID: "provider10",
    category: "Others",
    banner: `${ROOT_PATH}gt-sword.png`,
  },
  "11": {
    id: "11",
    name: "Wasak Rush",
    providerID: "10",
    category: "Slots",
    banner: `${ROOT_PATH}oblivion-saga.png`,
  },
  "12": {
    id: "12",
    name: "Medal of Honor",
    providerID: "6",
    category: "New",
    banner: `${ROOT_PATH}oblivion-saga.png`,
  },
  // Repeated entries with updated IDs
  "13": {
    id: "13",
    name: "Broomstick",
    providerID: "14",
    category: "Jackpots",
    banner: `${ROOT_PATH}ultima-1d.png`,
  },
  "14": {
    id: "14",
    name: "Tiger Claw",
    providerID: "9",
    category: "Jackpots",
    banner: `${ROOT_PATH}gt-sword.png`,
  },
  "15": {
    id: "15",
    name: "Pinoy Henyo",
    providerID: "18",
    category: "Others",
    banner: `${ROOT_PATH}ultima-1d.png`,
  },
  "16": {
    id: "16",
    name: "Samurai X",
    providerID: "2",
    category: "Others",
    banner: `${ROOT_PATH}oblivion-saga.png`,
  },
  "17": {
    id: "17",
    name: "Book of Wasak",
    providerID: "15",
    category: "Table Games",
    banner: `${ROOT_PATH}online-sabong.png`,
  },
  "18": {
    id: "18",
    name: "Crocodile Wasak",
    providerID: "1",
    category: "Others",
    banner: `${ROOT_PATH}oblivion-saga.png`,
  },
  "19": {
    id: "19",
    name: "Ultima Jackpot",
    providerID: "7",
    category: "Jackpots",
    banner: `${ROOT_PATH}online-sabong.png`,
  },
  "20": {
    id: "20",
    name: "Git Jackpot",
    providerID: "5",
    category: "Jackpots",
    banner: `${ROOT_PATH}oblivion-saga.png`,
  },
};
